#define NO_PYTHON_WARNINGS 0
#define NUITKA_COMPANY_NAME "Objection.lol"
#define NUITKA_MAIN_MODULE_NAME "__main__"
#define NUITKA_PRODUCT_NAME "Objection.lolClient"
#define NUITKA_VERSION_COMBINED "1.0.1.0"
#define PYTHON_HOME_PATH "C:\\Users\\help\\AppData\\Local\\Programs\\Python\\Python39"
#define SYSFLAG_BYTES_WARNING 0
#define SYSFLAG_NO_RANDOMIZATION 0
#define SYSFLAG_NO_SITE 0
#define SYSFLAG_OPTIMIZE 0
#define SYSFLAG_UNBUFFERED 0
#define SYSFLAG_UTF8 0
#define SYSFLAG_VERBOSE 0
